name: flutter_nav_toggle_example
description: Demo app for flutter_nav_toggle package.

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_nav_toggle:
    path: ..

flutter:
  uses-material-design: true
